# Generated by Django 3.1.7 on 2021-03-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App',
        ),
    ]
