# Generated by Django 3.0.7 on 2021-04-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_delhirestaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChennaiRestaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Chennai/Restaurants/Images')),
                ('location', models.TextField()),
                ('hreftag', models.TextField()),
            ],
        ),
    ]
