# Generated by Django 3.0.7 on 2021-04-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_kolkatarestaurants_mumbairestaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesMumbai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Images/Mumbai/Restaurants')),
                ('location', models.TextField()),
                ('hreftag', models.TextField()),
            ],
        ),
    ]
