# Generated by Django 3.0.7 on 2021-04-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_placesmumbai'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesChennai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Images/Chennai/Places')),
                ('location', models.TextField()),
                ('hreftag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlacesDelhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Images/Delhi/Places')),
                ('location', models.TextField()),
                ('hreftag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlacesKolkata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Images/Kolkata/Places')),
                ('location', models.TextField()),
                ('hreftag', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='placesmumbai',
            name='img',
            field=models.ImageField(upload_to='Images/Mumbai/Places'),
        ),
    ]
