# Generated by Django 3.0.7 on 2021-04-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20210430_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsDelhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Images/Delhi/Events')),
                ('location', models.TextField()),
                ('hreftag', models.TextField()),
            ],
        ),
    ]
