# Generated by Django 3.0.7 on 2020-06-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('number_ticket', models.IntegerField()),
                ('cost_per_ticket', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limit_per_person', models.IntegerField()),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Event Book',
                'verbose_name_plural': 'Event Books',
            },
        ),
        migrations.CreateModel(
            name='TableBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('person', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('occasion', models.CharField(blank=True, max_length=50)),
                ('special_request', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Table Book',
                'verbose_name_plural': 'Table Books',
            },
        ),
    ]
