# Generated by Django 3.0.7 on 2020-06-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbook',
            name='image',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
    ]
